### PR TITLE
Limit learning session

### PR DESCRIPTION
**Pull request by FischerRene**
I added the option to limit the current learning session to a certain amount of cards per learning session.
If no number is set, it will automatically be set to 0 and therefore not interfere with the current learning session.
Only numbers greater than 0 will limit the amout of cards used in each learning session.

One thing I noticed while testing: When clearing the local storage the `maxCardCount` gets removed as well but since the selection of the number is not dynamic, the number will not update even though it has been removed and will, if not set again, default to 0. If you have an idea how to change this behavior feel free to add it as a comment here or simply change change it in the code.
I personally dont think this is a real problem, so I would not change it, even though it could lead people to believe it is still set after deleting the local storage. I think the description of "clearLocalStorage" is representative enough.

### CODE REVIEW

**Comment by nikolockenvitz** [comment]
* the question mark icon is white instead of light grey and seems to be to far right and down (see third party decks as a better example)
* i find the spacing between the input and the button too large (even in the clear-local-storage-card there is a huge gap)
* the browser inserted steppers in the number input don't fit to the material ui IMO
* I understand that you want some feedback/confirmation but the snackbar on every update is a bit too much IMO
* btw if you remove the text content it will be `Successfully updated max card count to .`
* would you mind to have a consistent word like either `limit` or `max cards`?
* maybe a space between `has(have)` in the hint

**Comment by FischerRene** [comment]
> * he question mark icon is white instead of light grey and seems to be to far right and down (see third party decks as a better example)

I forgot to copy the class to make it light grey. Thanks. -> I could not spot where the icon of third party decks is moved and therefore did not change it here. **Do you have any idea where we made this change?**

> * i find the spacing between the input and the button too large (even in the clear-local-storage-card there is a huge gap)

This was caused by the "v-message" of the input field of v-text-field -> I opted to auto hide it.

> * the browser inserted steppers in the number input don't fit to the material ui IMO

I thought about changing them already, but opted to simply remove them. My guess would be that no one uses them.

> * I understand that you want some feedback/confirmation but the snackbar on every update is a bit too much IMO

I get your point and removed the snackbars there completely. We may want to add a "settings changed" snackbar once we add more options to our settings menu.

> * btw if you remove the text content it will be `Successfully updated max card count to .`

Oh, did not test it before, but shouldn't cause an issue now, because empty strings will be updated to 0 once you start learning.

> * would you mind to have a consistent word like either `limit` or `max cards`?

I completely renamed the components and every other aspect of the new settings to "CardLimit". I think this should be more representative.

> * maybe a space between `has(have)` in the hint

I'd argue this is not necessary, but added it anyway.

<hr>

Feel free to add the last change necessary (move the icon) if you want to. You could also just leave another comment.

**Review by nikolockenvitz — APPROVED** [review]
Sounds good. Regarding saving: we could display a small icon indicating the app is (auto-)saving in the navbar.

I noticed some bugs during testing but fixed them directly. Btw you can't use `this.cardLimit === "0" || null` as JavaScript will see it as `(this.cardLimit === "0") || null` instead of what you was trying to do (`this.cardLimit === ("0" || null)`). That's probably not even working in Python, please never do this again 😄.
I also removed the steppers for Firefox, you were probably only working with some shady chromium based browser (How dare you!).

Didn't had a look into your code, just tested functionality which seems to work, thanks.

**Comment by FischerRene** [comment]
> Sounds good. Regarding saving: we could display a small icon indicating the app is (auto-)saving in the navbar.

Not quite sure what you have in mind. You mean like a icon poping up during the changes?
Will wait for an answer here before merging.

> I noticed some bugs during testing but fixed them directly. Btw you can't use `this.cardLimit === "0" || null` as JavaScript will see it as `(this.cardLimit === "0") || null` instead of what you was trying to do (`this.cardLimit === ("0" || null)`). That's probably not even working in Python, please never do this again 😄.

I'm not sure what my intentions were right there. I think it was something with default values, but not sure.

**Comment by nikolockenvitz** [comment]
> 
> Not quite sure what you have in mind. You mean like a icon poping up during the changes?
> Will wait for an answer here before merging.

like some disk icon glowing up for a second when its saving in the top right corner of the app (navbar); but we can add that later when we have more stuff in the settings

> 
> I'm not sure what my intentions were right there. I think it was something with default values, but not sure.

it was in the boolean expression of the ternary operator (see my fix bugs commit) :(

**Comment by FischerRene** [comment]
Seems like a good idea.

**Pull request merged**
